## 텐서(tensor)
! [텐서(Tensor)의 형태](https://codetorial.net/tensorflow/_images/basics_of_tensor_01.png)

In [1]:
"""
 텐서에서 사용되는 값은 "숫자"만 가능 
 텐서는 다차원 배열 의미함
 텐서는 벡터와 행렬을 일반화한 것으로 3차원으로 확장 가능 
 Tensorflow 패키지의 가장 주요한 객체가 tensor임 
 Tensorflow의 작업은 주로 텐서의 연산으로 이루어짐 
 Tensorflow의 정의 : 텐서(Tensor)를 정의하고 연산을 수행하도록하는 프레임 워크 

"""

'\n 텐서에서 사용되는 값은 "숫자"만 가능 \n 텐서는 다차원 배열 의미함\n 텐서는 벡터와 행렬을 일반화한 것으로 3차원으로 확장 가능 \n Tensorflow 패키지의 가장 주요한 객체가 tensor임 \n Tensorflow의 작업은 주로 텐서의 연산으로 이루어짐 \n Tensorflow의 정의 : 텐서(Tensor)를 정의하고 연산을 수행하도록하는 프레임 워크 \n\n'

In [2]:
# numpy의 array()를 이용해서 텐서 형태 확인
# 스칼라(scala) 테선 => 0차원 텐서, 0D텐서, rank0인 텐서라고 다양하게 칭함
# 하나의 숫자만 담고 있는 텐서 
# 하나의 값을 가지는 일반 변수라고 생각하면 이해편함 


In [3]:
import numpy as np 
x = np.array(12)
print("스칼라 텐서: ", x)
print("차원", x.shape)
print("rank확인", x.ndim)

스칼라 텐서:  12
차원 ()
rank확인 0


In [7]:
# 벡터(vector) 텐서 : 1D 텐서, rnak1텐서
# 여러가지 숫자를 담고 있는 1차원 배열
# 1차원 리스트[]와 유사한 형태

x = np.array([12,3,6,14,7])
print("5개의 값을 가지는 벡터: ", x)
print("차원", x.shape)
print("rank확인", x.ndim)
print(x[2])

5개의 값을 가지는 벡터:  [12  3  6 14  7]
차원 (5,)
rank확인 1
6


In [13]:
# 행렬(Matrix) 텐서 : 2D 텐서, rank2텐서 
# 여러개의 벡터를 담고 있는 새로운 배열을 행렬(matrix)텐서라 칭함
# 2차원 : [[]]이 형태
# 데이터 프레임 형태와 유사 

x =np.array([[5,78,2,34,0],
           [6,79,3,35,1],
           [7,80,4,36,2]])
print("행렬: ", x)
print("차원", x.shape)
print("rank확인", x.ndim)
x[:,0]

행렬:  [[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]
차원 (3, 5)
rank확인 2


array([5, 6, 7])

In [ ]:
# 3D 텐서 : rank3 텐서 
# 행렬이 여러개 모여 있는 것 
# 숫자가 채워진 직육면체


In [15]:
x =np.array([[[5,78,2,34,0],[6,79,3,35,1],[7,80,4,36,2]],
            [[5,78,2,34,0],[6,79,3,35,1],[7,80,4,36,2]],
            [[5,78,2,34,0],[6,79,3,35,1],[7,80,4,36,2]]])
print("3D텐서: ", x)
print("차원", x.shape)
print("rank확인", x.ndim)
x[1,1]

3D텐서:  [[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]
차원 (3, 3, 5)
rank확인 3


array([ 6, 79,  3, 35,  1])