### 05_생선 분류데이터셋.csv 파일 읽어 들인 후 정보 확인 

컬럼 정보 
- species : 종류
- weight : 무게
- diagonal : 대각선 길이 
- height : 높이
- width : 두께 

In [131]:
import pandas as pd
import numpy as np

In [132]:
fish = pd.read_csv("./data/05_생선_분류_데이터셋.csv")
fish.info()
fish.describe()
fish

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Species   159 non-null    object 
 1   Weight    159 non-null    float64
 2   Length    159 non-null    float64
 3   Diagonal  159 non-null    float64
 4   Height    159 non-null    float64
 5   Width     159 non-null    float64
dtypes: float64(5), object(1)
memory usage: 7.6+ KB


Species  Weight  Length  Diagonal   Height   Width
0     Bream   242.0    25.4      30.0  11.5200  4.0200
1     Bream   290.0    26.3      31.2  12.4800  4.3056
2     Bream   340.0    26.5      31.1  12.3778  4.6961
3     Bream   363.0    29.0      33.5  12.7300  4.4555
4     Bream   430.0    29.0      34.0  12.4440  5.1340
..      ...     ...     ...       ...      ...     ...
154   Smelt    12.2    12.2      13.4   2.0904  1.3936
155   Smelt    13.4    12.4      13.5   2.4300  1.2690
156   Smelt    12.2    13.0      13.8   2.2770  1.2558
157   Smelt    19.7    14.3      15.2   2.8728  2.0672
158   Smelt    19.9    15.0      16.2   2.9322  1.8792

[159 rows x 6 columns]

### 데이터 분리하기1 ( 독립변수, 종속변수) 

In [ ]:
# 로지스틱회귀 -> 분류도 가능
# 분류시 타겟 -> 카테고리 형태
# 시계열 타겟 -> 연속형 
# 분류시 타입 -> 오브젝트 여야 한다 

In [134]:
# 생선의 종류 조회 
fish['Species'].unique()
pd.unique(fish["Species"])

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [ ]:
# 이진 분류 : 2개 중 하나
# 다중 분류 : 여러개중 하나 
# 종속 변수 : 생선 종류 
# 독립변수 : 종류 제외 나머지

In [135]:
# 데이터 분리하기1 (독립변수, 종속변수) 

fish_target = fish['Species']
fish_input = fish[["Weight",'Length','Diagonal','Height','Width']]

print(fish_target.shape, fish_input.shape)

(159,) (159, 5)


### 데이터 형태 변경하기

In [136]:
# 데이터 형태 변경하기 
fish_input = fish_input.to_numpy()
fish_target = fish_target.to_numpy()
print(fish_target.shape, fish_input.shape)
fish_target

(159,) (159, 5)


array(['Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Whitefish',
       'Whitefish', 'Whitefish', 'Whitefish', 'Whitefish', 'Whitefish',
       'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki',
       'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perc

### 데이터 분리하기 2 (훈련데이터, 테스트 데이터)

In [137]:
#훈련데이터와 test데이터 분리하기 75 :25
# train_test_split : 분류하는 lib 기본 75:25 
from sklearn.model_selection import train_test_split
train_input, test_input,train_target, test_target = train_test_split(fish_input, fish_target, test_size = 0.25, random_state = 42)
print(train_input.shape, train_target.shape)
print (test_input.shape, test_target.shape)

(119, 5) (119,)
(40, 5) (40,)


### 데이터 정규화하기

In [138]:
# 정규화(표준화) 처리하기 : 다양한 단위의 범위를 일괄적인 범위로 맞추기 위해 한다
# standerd 사용
# - 변수 : train_scaled, test_scaled 

# 라이브러리 
from sklearn.preprocessing import StandardScaler

#함수 불러오기 
ss = StandardScaler()

# 스스로 표준 점수 생성
ss.fit(train_input)

#훈련데이터를 표준 점수로 변환하기 
train_scaled = ss.transform(train_input)

#테스트데이터를 표준점수로 변환하기 
test_scaled = ss.transform(test_input)

print(train_scaled.shape, test_scaled.shape)


(119, 5) (40, 5)


# KNN으로 확률적 분류 해보기 

In [76]:
# 문자가 들어 있다 : 분류 
# KNN 분류 해보기  
# 잘한다 못한다 -> 확률적 알고리즘 
# 독립변수로 종속변수의 값을 맞출 것인데 이는 확률적으로 맞추는 것이다 
# KNN은 지도학습, 확률적 예측을 한다 

In [77]:
# KNN(최금점이웃 알고리즘) 분류 모델로 훈련(fit) 및 검증(score)하기 
# 패키지 : sklearn.neighbors
# 클래스 : KNeighborsClassifier
# 이웃의 개수 : 3개 
# 모델 변수 : kn

from sklearn.neighbors import KNeighborsClassifier
# 클래스 모델 생성 
kn = KNeighborsClassifier(n_neighbors = 3)
kn

KNeighborsClassifier(n_neighbors=3)

In [78]:
# 훈련모델 생성
kn.fit(train_scaled, train_target )

KNeighborsClassifier(n_neighbors=3)

In [79]:
# 훈련데이터 정확도 확인 
print(kn.score(train_scaled, train_target))
# 테스트 데이터의 정확도 확인

print(kn.score(test_scaled, test_target))
# 약간의 과대적합 

0.8907563025210085
0.85


C:\Users\ekdms\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\ekdms\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

In [80]:
# 종속변수의 값 확인 
pd.unique(fish['Species'])

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [81]:
# kn모델이 가지고 있는 종속변숭의 순서 확인하기 -> ABC 순서 
# 모델이 가지고 있는 종속변수의 순서는 알파벳 오름차순 순서로 정렬되어 있다 
kn.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [82]:
# 테스트 데이터에서 상위 5개 데이터만 추출 
test_scaled[0:5]

array([[-0.88741352, -0.91804565, -1.03098914, -0.90464451, -0.80762518],
       [-1.06924656, -1.50842035, -1.54345461, -1.58849582, -1.93803151],
       [-0.54401367,  0.35641402,  0.30663259, -0.8135697 , -0.65388895],
       [-0.34698097, -0.23396068, -0.22320459, -0.11905019, -0.12233464],
       [-0.68475132, -0.51509149, -0.58801052, -0.8998784 , -0.50124996]])

In [83]:
# 5개의 테스트 데이터로 예측하기 
kn.predict(test_scaled[:5])

C:\Users\ekdms\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array(['Perch', 'Smelt', 'Pike', 'Perch', 'Perch'], dtype=object)

In [84]:
test_target[:5]

array(['Perch', 'Smelt', 'Pike', 'Whitefish', 'Perch'], dtype=object)

In [85]:
import numpy as np 
np.column_stack((test_target[:5],kn.predict(test_scaled[:5])))

C:\Users\ekdms\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([['Perch', 'Perch'],
       ['Smelt', 'Smelt'],
       ['Pike', 'Pike'],
       ['Whitefish', 'Perch'],
       ['Perch', 'Perch']], dtype=object)

In [86]:
# 5개 데이터에 대한 확률적으로 계산된 값 확인하기 
# 조회된 값 : 확률 값 (1 :100%)
# 각 행의 데이터가 들어 왔을 때 생선 종류 중 어떤 것인지 확률적으로 보여 줌 
proba = kn.predict_proba(test_scaled[:5])
np.round(proba, decimals =4)

array([[0.    , 0.    , 1.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    , 1.    , 0.    ],
       [0.    , 0.    , 0.    , 1.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.6667, 0.    , 0.3333, 0.    , 0.    ],
       [0.    , 0.    , 0.6667, 0.    , 0.3333, 0.    , 0.    ]])

# 로지스틱회귀 분류모델 (Logistic Regression)

In [87]:
# 일반적 사용 분류모델은 확률적으로 체크 되고 있다 
# KNN은 실무에서 잘 사용하지 않는다 -> 근사치에 있는것은 정화깋 확인, but 거리가 생기면 오차률이 높아진다 
# 로지스틱 레그리에이션 분류모델 초창기에는 많이 사용 -> but 랜덤포레스트, 그리드부스팅이 나오면서 잘 사용 X
# 그리드 부스팅이 많이 사용 

In [94]:
# 분류 모델은 이진 분류와 다중분류로 구분된다 
# - 이진분류 : 둘 중 한개를 선택, 시그모이드(sigmoid)알고리즘이 내부적으로 사용된다
#     *시그모이드 : 0과 1로 구분하는 알고리즘 (두개중 하나선택) 

# - 다중분류 : 3개이상 중에 선택, 소프트맥스(softmax) 알고리즘이 내부적으로 사용된다 
#     *소프트맥스 : 여러개 중에 확률적으로 구분하는 알고리즘 (여러개중 하나 선택)

#  시그모이드와 소프트 맥스 중에 선택해야 하는 경우도 있다 
# 종속변수가 여러개 : 소프트맥스

In [98]:
train_target

array(['Bream', 'Pike', 'Smelt', 'Perch', 'Parkki', 'Roach', 'Perch',
       'Bream', 'Perch', 'Perch', 'Perch', 'Bream', 'Perch', 'Parkki',
       'Perch', 'Bream', 'Smelt', 'Perch', 'Roach', 'Bream', 'Pike',
       'Bream', 'Pike', 'Perch', 'Parkki', 'Bream', 'Perch', 'Pike',
       'Bream', 'Perch', 'Parkki', 'Roach', 'Perch', 'Bream', 'Roach',
       'Perch', 'Bream', 'Bream', 'Perch', 'Perch', 'Roach', 'Pike',
       'Perch', 'Smelt', 'Pike', 'Roach', 'Perch', 'Parkki', 'Perch',
       'Bream', 'Perch', 'Smelt', 'Perch', 'Parkki', 'Smelt', 'Perch',
       'Perch', 'Roach', 'Bream', 'Perch', 'Perch', 'Roach', 'Roach',
       'Perch', 'Perch', 'Bream', 'Roach', 'Bream', 'Roach', 'Parkki',
       'Perch', 'Perch', 'Perch', 'Perch', 'Pike', 'Pike', 'Perch',
       'Bream', 'Perch', 'Bream', 'Whitefish', 'Pike', 'Bream', 'Bream',
       'Roach', 'Perch', 'Pike', 'Bream', 'Pike', 'Parkki', 'Roach',
       'Perch', 'Roach', 'Smelt', 'Whitefish', 'Roach', 'Perch', 'Bream',
       'Whitefi

# 로지스틱회귀분류 - 이진분류 

In [102]:
#이진분류를 하고 싶다 -> 데이터 쪼개기 
# 이진 분류를 위한 데이터로 재구성 하기 : bream 과 Smelt 값 사용 

bream_smelt_index = (train_target == 'Bream') | (train_target == 'Smelt')
print(bream_smelt_index)

# 훈련에 사용할 독립변수와 종속변수 데이터 추출하기 
train_bream_smelt = train_scaled[bream_smelt_index]
target_bream_smelt = train_target[bream_smelt_index]
print(train_bream_smelt)

[ True False  True False False False False  True False False False  True
 False False False  True  True False False  True False  True False False
 False  True False False  True False False False False  True False False
  True  True False False False False False  True False False False False
 False  True False  True False False  True False False False  True False
 False False False False False  True False  True False False False False
 False False False False False  True False  True False False  True  True
 False False False  True False False False False False  True False False
 False  True False  True False False  True  True False False False False
 False False False False  True  True False False  True False False]
[[ 0.91965782  0.60943175  0.81041221  1.85194896  1.00075672]
 [-1.0858536  -1.68646987 -1.70848587 -1.70159849 -2.0044758 ]
 [ 0.63818253  0.56257661  0.73223951  1.64473401  0.50705737]
 [ 0.30041219  0.23459067  0.42823457  1.36042157  0.22329758]
 [ 0.9027693   0.703142

In [103]:
# 훈련하기 
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(train_bream_smelt, target_bream_smelt)
lr.score(train_bream_smelt, target_bream_smelt)

1.0

In [104]:
# 상위 5개만 예측하여, 종속변수들에 대한 확률값 확인하기 
# 0번째 :Bream, 1번째 : Smelt 
lr.predict_proba(train_bream_smelt[:5])

array([[0.99759855, 0.00240145],
       [0.02735183, 0.97264817],
       [0.99486072, 0.00513928],
       [0.98584202, 0.01415798],
       [0.99767269, 0.00232731]])

In [105]:
lr.classes_

array(['Bream', 'Smelt'], dtype=object)

In [106]:
# 시그모이드 결과값 확인해보기 
# 음수 : 왼쪽편, 양수 : 오른쪽 편
# 0 보다 작으면 0, 0보다 크면 1
lr.decision_function(train_bream_smelt[:5])

array([-6.02927744,  3.57123907, -5.26568906, -4.24321775, -6.0607117 ])

# 로지스틱회귀 - 다중분류

In [107]:
lr = LogisticRegression()
lr.fit(train_scaled, train_target)
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

# KNN 
# 0.8907563025210085
# 0.85
# # 로지스틱 
# 0.8067226890756303
# 0.85
# 예측 률이 더 낮다 

0.8067226890756303
0.85


In [121]:
# - C : 규제강도 조절값 (릿지 라쏘 모델의 alpha와 동일)
#     : alpha 값의 경우 클수록 강도가 커졌다면 
#         C의 값을 작을 수록 강도가 커진다 
#     : 기본값은 1
#      기본값보다 큰값을 사용했기에 강도를 완화했다고 표현한다 

# - max_iter : 훈련반복횟수 
#     : 기본값 :100 
#     : 훈련 중 반복횟수를 초과하여 훈련을 해야하는 경우 (모델이 알아서)
#      경고창이 뜨는 경우 있음, 그래서 반복 회수를 크게 잡아도 된다 

lr = LogisticRegression(C=20,max_iter=1000)
lr.fit(train_scaled, train_target)
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))
# C 값을 늘일수록 과적합이 커진다 -> max_iter 를 이용해 가장 적절한 값을 찾는다 
# 가장 적절한 값을 못찾으면 계속 한다 못찾았는데 종료되면 -> 경고창이 뜬다 

0.9327731092436975
0.925


In [122]:
# 상위 5개 데이터만 예측해보기 
lr.predict(train_scaled[:5])

array(['Bream', 'Pike', 'Smelt', 'Perch', 'Parkki'], dtype=object)

In [124]:
# 확률값 확인하기 
proba = lr.predict_proba(test_scaled[:5])
print(np.round(proba, decimals=3))
print(lr.classes_)

[[0.    0.014 0.841 0.    0.136 0.007 0.003]
 [0.    0.003 0.044 0.    0.007 0.946 0.   ]
 [0.    0.    0.034 0.935 0.015 0.016 0.   ]
 [0.011 0.034 0.306 0.007 0.567 0.    0.076]
 [0.    0.    0.904 0.002 0.089 0.002 0.001]]
['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']


In [126]:
## 소프트 맥스 알고리즘을 이용하여 확률 값 확인하기 
# 지수화된 데이터 삽입 -> 확률적으로 보여 줌 
from scipy.special import softmax
decision = lr.decision_function(test_scaled[:5])
proba = softmax(decision, axis = 1)
print(np.round(proba, decimals = 3))


[[0.    0.014 0.841 0.    0.136 0.007 0.003]
 [0.    0.003 0.044 0.    0.007 0.946 0.   ]
 [0.    0.    0.034 0.935 0.015 0.016 0.   ]
 [0.011 0.034 0.306 0.007 0.567 0.    0.076]
 [0.    0.    0.904 0.002 0.089 0.002 0.001]]
